import { Palette, ScrollView } from "std-widgets.slint";

export struct Route {
    name: string,
    description: string}

export struct Category {
    name: string,
    routes: [Route]
}

component CategoryCard {
    in property <string> category;
    in property <int> i;

    callback clicked();

    ta := TouchArea {
        background := Rectangle {
            background: Palette.accent-background.with-alpha(0.3);
            animate background {
                duration: 200ms;
                easing: ease-in-out;
            }
            border-color: Palette.border;
            border-width: 1px;
            border-radius: 12px;

            Text {
                text: category;
                font-size: 28px;
            }
        }

        clicked => {
            clicked();
        }
    }

    states [
        hover when ta.has-hover: {
            background.background: Palette.accent-background.with-alpha(0.5);
        }
    ]
}

export component CategoryPicker {
    in property <[Category]> categories;

    property <length> scrollable-width: 452px;
    property <length> tile-height: 62px;
    property <length> gap: 8px;

    callback selected(i: int);

    Rectangle {
        ScrollView {
            width: 100%;
            viewport-width: scrollable-width;
            viewport-height: floor(categories.length / 2) * (tile-height + gap) - gap;

            for category[i] in categories: CategoryCard {
                category: category.name;
                i: i;

                x: mod(i, 2) * scrollable-width / 2 + gap / 2;
                y: floor(i / 2) * (tile-height + gap);
                width: scrollable-width / 2 - gap;
                height: tile-height;

                clicked => {
                    selected(i);
                }
            }
        }
    }
}
