import { GroupBox, VerticalBox, StandardTableView, Button, ScrollView, Palette, HorizontalBox } from "std-widgets.slint";
import { BrainDimensions } from "MainPicker.slint";
export component DiagnosticsPopup {
    in property <[[StandardListViewItem]]> diagnostics;
    callback calibrate();
    callback done();

    Rectangle {
        // Hardcoded width and height from the size of the V5 brain
        width: BrainDimensions.width;
        height: BrainDimensions.height;
        background: Palette.background;

        Image {
            x: parent.width - self.width;
            y: parent.height - self.height;
            opacity: 0.2;
            source: @image-url("./assets/doxa-logo-cropped.png");
        }

        VerticalLayout {
            padding: 8px;
            HorizontalLayout {
                height: 28px;
                spacing: 8px;
                Text {
                    text: "Diagnostics";
                    font-size: 24px;
                    horizontal-stretch: 1;
                }

                Button {
                    text: "Calibrate gyro";
                    clicked => {
                        calibrate()
                    }
                }

                Button {
                    text: "Done";
                    clicked => {
                        done()
                    }
                }
            }

            VerticalLayout {
                vertical-stretch: 1;

                StandardTableView {
                    width: 100%;
                    height: 100%;

                    columns: [
                        { title: "Name" },
                        { title: "Value" },
                    ];
                    rows: diagnostics;
                }
            }
        }
    }
}
